# Offline detection weights

ENTROPY_WEIGHT = 20
LONG_LABEL_WEIGHT = 10
DIGIT_RATIO_WEIGHT = 10
QUERY_RATE_WEIGHT = 20
UNIQUE_SUBDOMAIN_WEIGHT = 10
TIMING_WEIGHT = 10
LABEL_COUNT_WEIGHT = 20


# Live detection weights
# Total = 100

LIVE_ENTROPY_WEIGHT = 25
LIVE_LONG_LABEL_WEIGHT = 15
LIVE_QUERY_RATE_WEIGHT = 25
LIVE_UNIQUE_SUBDOMAIN_WEIGHT = 15
LIVE_TIMING_WEIGHT = 20


# Detection severity thresholds

LOW_THRESHOLD = 30
MEDIUM_THRESHOLD = 60
HIGH_THRESHOLD = 80